# -*- coding: utf-8 -*-
"""IPL_Data_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-iXeVWWSD0CQE0iJHMkGEkMWIf0EFwll
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

matches = pd.read_csv('matches.csv')
deliveries = pd.read_csv('deliveries.csv')

print(matches.shape)
print(deliveries.shape)
matches.head()

deliveries.head()

print(deliveries.columns.tolist())

print(matches.isnull().sum())

matches = matches.dropna(subset=['winner'])
matches['city'] = matches['city'].fillna('unknown')
matches['player_of_match'] = matches['player_of_match'].fillna('unknown')

print(matches.isnull().sum())

matches.head()

win_counts = matches['winner'].value_counts()
print(win_counts)

"""## Visualization 1: Most Matches Won by Each Team
**Insight:** Mumbai Indians have won the most matches in IPL history,
followed by Chennai Super Kings. These two teams are the most
consistent performers in IPL.
"""

plt.figure(figsize=(12,6))
sns.barplot(x=win_counts.values, y=win_counts.index, palette='rocket')
plt.title('Most Matches Won by Each Team')
plt.xlabel('Number of Wins')
plt.ylabel('Team')

"""## Visualization 2: Toss Winner vs Match Winner
**Insight:** Winning the toss does not guarantee winning the match.
Nearly 50% of the time, the toss winner goes on to lose the match.
"""

toss_win = matches[matches['toss_winner'] == matches['winner']]
toss_loss = matches[matches['toss_winner'] != matches['winner']]
label = ['Toss Winner Won Match', 'Toss Winner Lost Match']
sizes = [len(toss_win), len(toss_loss)]
plt.pie(sizes, labels=label, autopct='%1.1f%%', startangle=140)
plt.title('Toss Winner & Match Winner')
plt.show()

"""## Visualization 3: Top 10 Run Scorers
**Insight:** Virat Kohli leads the all-time run scoring charts in IPL,
followed by Rohit Sharma. Both players have been incredibly consistent
over the years.
"""

top_scorers = deliveries.groupby('batter')['batsman_runs'].sum().sort_values(ascending=False).head(10)
plt.figure(figsize=(12,6))
sns.barplot(x=top_scorers.values, y=top_scorers.index, palette='magma', legend="false" )
plt.title('Top 10 Run Scorers in IPL History')
plt.xlabel('Total Runs')
plt.ylabel('Batsman')
plt.show()

"""## Visualization 4: Top 10 Wicket Takers
**Insight:** Lasith Malinga is the highest wicket taker in IPL history
(2008-2020). His yorker deliveries made him nearly unplayable in
death overs.
"""

wickets = deliveries[deliveries['dismissal_kind'].notna()]
top_bowlers = wickets.groupby('bowler')['dismissal_kind'].count().sort_values(ascending=False).head(10)

plt.figure(figsize=(12,6))
sns.barplot(x=top_bowlers.values, y=top_bowlers.index, palette='coolwarm')
plt.title('Top 10 Wicket Takers in IPL History')
plt.xlabel('Total Wickets')
plt.ylabel('Bowler')
plt.tight_layout()
plt.show()

"""## Visualization 5: Season-wise Total Runs
**Insight:** Total runs scored per season has increased over the years,
indicating that batting has become more dominant in IPL over time.
"""

match_runs = deliveries.groupby('match_id')['total_runs'].sum().reset_index()
print(match_runs.head())
season_runs = match_runs.merge(matches[['id','season']], left_on='match_id', right_on='id')
season_total = season_runs.groupby('season')['total_runs'].sum()
plt.plot(season_total.index, season_total.values, marker='o', color='orange', linewidth=1)
plt.title('Season-wise Total Runs Scored in IPL')
plt.xlabel('Season')
plt.ylabel('Total Runs')
plt.xticks(rotation=45)
plt.show()
print(season_total)

from google.colab import files
uploaded = files.upload()

"""## Visualization 6: Most Player of the Match Awards
**Insight:** AB de Villiers and Chris Gayle have won the most
Player of the Match awards in IPL history. Their match-winning
performances have been extraordinary over the years.
"""

top_players = matches['player_of_match'].value_counts().head(10)
print(top_players)
plt.figure(figsize=(12,6))
sns.barplot(x=top_players.values, y=top_players.index, hue=top_players.index, palette='viridis')
plt.title('Most Player of the Match Awards')
plt.xlabel('Number of Awards')
plt.ylabel('Player')
plt.show()

each_match_fours = deliveries[deliveries['batsman_runs']==4].groupby('match_id')['batsman_runs'].count().reset_index()
each_match_sixes = deliveries[deliveries['batsman_runs']==6].groupby('match_id')['batsman_runs'].count().reset_index()
print(each_match_fours.head())
print(each_match_sixes.head())

fours = each_match_fours.merge(matches[['id','season']], left_on='match_id', right_on='id')
sixes = each_match_sixes.merge(matches[['id','season']], left_on='match_id', right_on='id')
print(fours.head())
print(sixes.head())

season_fours = fours.groupby('season')['batsman_runs'].count()
season_sixes = sixes.groupby('season')['batsman_runs'].count()
print(season_fours)
print(season_sixes)

"""## Visualization 7: Season-wise Fours and Sixes
**Insight:** 2013 season had the most boundaries in IPL history.
Over the years, the number of sixes has increased significantly,
showing that batsmen are playing more aggressively.
"""

plt.figure(figsize=(12,6))
plt.bar(season_fours.index, season_fours.values, label='Fours', color='blue', alpha=0.7)
plt.title('Season-wise Fours')
plt.xlabel('Season')
plt.ylabel('Count')
plt.xticks(rotation=45)
plt.show()

plt.figure(figsize=(12,6))
plt.bar(season_sixes.index, season_sixes.values, label='Sixes', color='red', alpha=0.7)
plt.title('Season-wise Sixes')
plt.xlabel('Season')
plt.ylabel('Count')
plt.xticks(rotation=45)
plt.show()

"""## Visualization 8: Winning by Runs vs Wickets
**Insight:** More matches are won by wickets than by runs in IPL.
This shows that chasing teams have a slight advantage over
defending teams.
"""

win_by_runs = matches[matches['result'] == 'runs']['result'].count()
win_by_wickets = matches[matches['result'] == 'wickets']['result'].count()

print(win_by_runs)
print(win_by_wickets)

labels = ['Won by Runs', 'Won by Wickets']
sizes = [win_by_runs, win_by_wickets]

plt.figure(figsize=(7,7))
plt.pie(sizes, labels=labels, autopct='%1.1f%%',
        colors=['#3498DB','#E74C3C'], startangle=140,
        explode=(0.05, 0.05))
plt.title('Winning by Runs vs Wickets')
plt.show()

"""## Visualization 9: Top 10 Venues by Number of Matches
**Insight:** Wankhede Stadium and M. Chinnaswamy Stadium have
hosted the most IPL matches. These venues are known for their
batting-friendly pitches and electric atmospheres.
"""

top_venues = matches['venue'].value_counts().head(10)
plt.figure(figsize=(12,6))
sns.barplot(x=top_venues.values, y=top_venues.index,
            hue=top_venues.index, palette='Set2')
plt.title('Top 10 Venues by Number of Matches')
plt.xlabel('Number of Matches')
plt.ylabel('Venue')
plt.show()

"""## Visualization 10: Top 10 Batsmen by Average Runs per Ball
**Insight:** Hard-hitting batsmen dominate the average runs per
ball chart. These players have the ability to score quickly and
change the game in a few overs.
"""

avg_runs = deliveries.groupby('batter')['batsman_runs'].mean().sort_values(ascending=False).head(10)
plt.figure(figsize=(12,6))
sns.barplot(x=avg_runs.values, y=avg_runs.index,
            hue=avg_runs.index, palette='cubehelix')
plt.title('Top 10 Batsmen by Average Runs per Ball')
plt.xlabel('Average Runs')
plt.ylabel('Batsman')
plt.show()

"""## Conclusion
This analysis of IPL data from 2008 to 2024 reveals that Mumbai
Indians are the most successful team, Virat Kohli is the leading
run scorer, and batting has become more dominant over the years.
Toss winning does not significantly impact match results.
"""